project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!blog/"

website:
  favicon: files/NH.png
  title: "Niklas Hlubek"
  site-url: https://nhlubek.github.io
  description: "Niklas Hlubek, epidemiologist and statistical programmer working on real-world evidence and drug safety at UMC Utrecht."
  image: files/NH.png
  open-graph: true
  twitter-card:
    card-style: summary
  navbar:
    search: true
    collapse: true
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV
      - href: research.qmd
        text: Research 
    right:
      - icon: github
        href: https://github.com/nhlubek
        text: GitHub
  back-to-top-navigation: true
  page-footer:
    left: "© 2026 Niklas Hlubek"
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles-extras.css
    toc: true
    smooth-scroll: true
    email-obfuscation: javascript
    page-layout: article
    code-copy: true
    
