project:
  type: website
  output-dir: docs

website:
  favicon: files/NH.png
  title: "**Niklas Hlubek**"
  navbar:
    search: true
    collapse: true
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV
      - href: research.qmd
        text: Research 
    right:
      - icon: github
        href: https://github.com/nhlubek
        text: GitHub
  back-to-top-navigation: true


format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Computer Modern, sans-serif;
    css: styles-extras.css
    toc: true
    smooth-scroll: true
    email-obfuscation: javascript
    page-layout: article
    code-copy: true
    
